services:
  postgres-db:
    image: postgres:18
    environment:
      POSTGRES_DB: agentview
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  postgres-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres-db
    volumes:
      - ./docker/pg-admin/servers.json:/pgadmin4/servers.json

volumes:
  pgdata: